### ISSUE TITLE
Τεχνικά προβλήματα στις ασκήσεις γραμμής εντολών

### ISSUE THREAD

**Issue by IsabellaPap** [courses-ionio/dokey#1]
Επιχειρώ να κάνω κάποιες ασκήσεις στο bash για τις οποίες χρειάζομαι να κατεβάσω κάποια torrents.
Στην αρχή επιχείρησα να κάνω search torrents στο browser μου, αλλά για κάποιο λόγο, μετά από τόσα χρόνια που χρησιμοποιώ torrent search site όπως το pirate bay και το 1337x, κάποια ελληνική επιτροπή ονόματι [ΕΔΠΠΙ](https://opi.gr/edppi_block/edppi_block.html), μου μπλοκάρει την πρόσβαση στα site. 
Δοκίμασα να χρησιμοποιήσω το we-get για να κάνω search  torrents μέσω του bash, αλλά δε δούλεψε, υποψιάζομαι επειδή χρηισμοποιεί τα ίδια site με την ίδια IP, και δεν έχει πρόσβαση ούτε το ίδιο. 
Αναλυτικότερα δείτε το σχετικό asciinema για την προσπάθεια μου με το we-get:
[![asciicast](https://asciinema.org/a/368764.svg)](https://asciinema.org/a/368764)

Δεν έχω πολύ εμπειρία με proxy κλπ, ξέρω ότι θα μπορούσα να χρησιμοποιήσω VPN αλλά δεν έχω τα χρήματα να διαθέσω για αυτό αυτή τη στιγμή. Κάνω νέο issue μήπως έχετε κάποιον ασφαλή και δοκιμασμένο τρόπο να μου προτείνετε αλλιώς αναγκαστικά θα αφήσω τις 2 ασκήσεις που ξεκίνησα μισές και θα ξεκινήσω κάποια άλλη.
Ευχαριστώ.

**Comment by moya10** [comment]
εχεις δοκιμασει να βαλεις openvpn; μπορεις να βρεις ελευθερα πιστοποιητικα στο vpnbook. Δεν εχω δοκιμασει ακομη αν τοτε θα τρεξει η εντολη σου, αλλα ισως σε βοηθησει. Επισης η ασκηση νομιζω ζηταει χρηση torque...

**Comment by IsabellaPap** [comment]
το torque δεν δουλεύει, το AUR δεν μου το κατεβάζει καν, ούτε από το terminal, κάνει πάντα fail to build. Έτσι βρήκα ένα "alternative" αν και στα tags αναφερεται και το transmission. Το we-get είναι μόνο για αναζήτηση, ως εναλλακτική στο πρόβλημα που είχα και να αποφύγω ακόμα καλύτερα τα malware από το browser.
Edit: Eυχαριστώ για την συμβουλή, δυστυχώς το openvpn δεν υποστηρίζεται ακόμα σε ArchLinux αλλά βρήκα αντίστοιχο (qopenvpn)

**Comment by moya10** [comment]
So..
1. change DNS:
sudo apt-get install resolvconf // sudo systemctl enable resolvconf.service // sudo systemctl start resolvconf.service
sudo nano /etc/resolvconf/resolv.conf.d/base -> add nameserver (there are free IPs available.. again)
sudo nano /etc/network/interfaces -> at the top add source /etc/network/interfaces.d/*, at the bottom add dns-nameserver x.x.x.x
sudo systemctl restart NetworkManager // sudo systemctl restart resolvconf.service
2. setup  vpn (whatever you want...) check dnsleak to see that it works...
3. install transmission-daemon
sudo apt-get install transmission-daemon
sudo systemctl stop transmission-daemon
sudo nano /etc/transmission-daemon/settings.json -> replace any true/false value that might break your job, save
sudo systemctl start transmission-daemon

For torque 
clone or download zip folder from [here](https://github.com/dylanaraps/torque) 
unzip it, cd to your unzippedFolder 
run chmod +x torque
run ./torque

For we-get
sudo apt-get install python3-pip
sudo pip3 install git+https://github.com/rachmadaniHaryono/we-get
sudo we-get --search "blade runner"

Results

![we-get-success](https://user-images.githubusercontent.com/56644086/98162463-4d62f700-1ed9-11eb-826b-bb5724bed15c.png)
![torque-fail](https://user-images.githubusercontent.com/56644086/98162717-ad599d80-1ed9-11eb-8931-56fce307f46d.png)
